"""init

Revision ID: f027e92c18ce
Revises: 
Create Date: 2024-10-16 18:30:21.674199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f027e92c18ce'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telethon_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('api_id', sa.BigInteger(), nullable=True),
    sa.Column('api_hash', sa.String(), nullable=True),
    sa.Column('date_create', sa.DateTime(timezone=True), nullable=True),
    sa.Column('session_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telethon_accounts_id'), 'telethon_accounts', ['id'], unique=False)
    op.create_table('fd_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('access_hash', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('date_create', sa.DateTime(timezone=True), nullable=True),
    sa.Column('telethon_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['telethon_id'], ['telethon_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fd_users_id'), 'fd_users', ['id'], unique=False)
    op.create_table('push_list',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('type_db', sa.String(), nullable=True),
    sa.Column('limit', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('text_push', sa.String(), nullable=True),
    sa.Column('media_list', sa.String(), nullable=True),
    sa.Column('date_push', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('telethon_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['telethon_id'], ['telethon_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_push_list_id'), 'push_list', ['id'], unique=False)
    op.create_table('rd_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('access_hash', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('date_create', sa.DateTime(timezone=True), nullable=True),
    sa.Column('telethon_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['telethon_id'], ['telethon_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rd_users_id'), 'rd_users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rd_users_id'), table_name='rd_users')
    op.drop_table('rd_users')
    op.drop_index(op.f('ix_push_list_id'), table_name='push_list')
    op.drop_table('push_list')
    op.drop_index(op.f('ix_fd_users_id'), table_name='fd_users')
    op.drop_table('fd_users')
    op.drop_index(op.f('ix_telethon_accounts_id'), table_name='telethon_accounts')
    op.drop_table('telethon_accounts')
    # ### end Alembic commands ###
